### ISSUE TITLE
i can install the app, but i can't open the app.

### ISSUE THREAD

**Issue by wumangxing1990** [sh1r0/caffe-android-demo#40]
I can install this app, but when i try to open the app by clicking the icon. It doesn't working.  The error information is as follows:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "sigfillset" referenced by "libcaffe.so"...
                                                                                at java.lang.Runtime.loadLibrary(Runtime.java:361)
                                                                                at java.lang.System.loadLibrary(System.java:525)
                                                                                at com.sh1r0.caffe_android_demo.MainActivity.<clinit>(MainActivity.java:55)
                                                                                at java.lang.Class.newInstanceImpl(Native Method)
                                                                                at java.lang.Class.newInstance(Class.java:1130)
                                                                                at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2282)
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:147)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:137)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5265)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by sh1r0** [comment]
Please let me know the arch and android version of your device.

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-demo/issues/21#issuecomment-218665445, and I'm afraid that your device is in a low api level (prior to 21).

**Comment by wumangxing1990** [comment]
yes, the android version of my device is 18

**Comment by sh1r0** [comment]
Then sorry for that, as I mentioned in https://github.com/sh1r0/caffe-android-demo/issues/21#issuecomment-218665802, it's a wontfix. BTW, https://github.com/sh1r0/caffe-android-demo/issues?q=sigfillset lead you to the answer.

**Comment by wumangxing1990** [comment]
thanks for answering
