### ISSUE TITLE
It works well using the default model, but after i change a model ,it crashes.

### ISSUE THREAD

**Issue by wumangxing1990** [sh1r0/caffe-android-demo#42]
I push another model to my android device and change the 'synset_words.txt'  file . But after i reinstall the app and try to launch it . It crashed. The error log is as follows:

11-10 10:57:39.464 2589-2589/? E/NativeLibraryUtils: Unable to locate gmscore in dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-2/lib/arm, /vendor/lib64, /system/lib64]]]
                                                     java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.gms-2/lib/arm/libgmscore.so" is 32-bit instead of 64-bit
                                                         at java.lang.Runtime.loadLibrary(Runtime.java:383)
                                                         at java.lang.System.loadLibrary(System.java:997)
                                                         at hyb.b(:com.google.android.gms:885)
                                                         at com.google.android.gms.common.security.ProviderInstallerImpl.a(:com.google.android.gms:202)
                                                         at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(:com.google.android.gms:1170)
                                                         at com.google.android.gms.common.security.ProviderInstallerImpl.insertProviderGated(:com.google.android.gms:101)
                                                         at com.google.android.gms.common.app.GmsApplication.onCreate(:com.google.android.gms:203)
                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:615)
                                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:2728)
                                                         at android.app.ActivityThread.access$2100(ActivityThread.java:165)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:135)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5669)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by sh1r0** [comment]
Is this related to #43?

**Comment by wumangxing1990** [comment]
According the error information ,it may can not find the file "/data/app/com.google.android.gms-2/lib/arm/libgmscore.so". But it is strange that it can run when i use the default alexnet. So i think maybe this app can only use alexnet  and it can not use VGGnet.

**Comment by sh1r0** [comment]
@wumangxing1990, I think it's basically an OOM issue.

Close #43.

**Comment by wumangxing1990** [comment]
Thank you very much
