### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed:

### ISSUE THREAD

**Issue by 18826485394** [sh1r0/caffe-android-demo#47]
**I have met this error,but I can't fix it.**
D/dalvikvm: Trying to load lib /data/app-lib/com.sh1r0.caffe_android_demo-1/libcaffe.so 0x4187f858
W/linker: cannot locate symbol "sigfillset" referenced by "libcaffe.so"...
W/linker: error:
E/dalvikvm: dlopen("/data/app-lib/com.sh1r0.caffe_android_demo-1/libcaffe.so") failed: dlopen failed: 
W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/sh1r0/caffe_android_demo/MainActivity;
W/dalvikvm: Class init failed in newInstance call (Lcom/sh1r0/caffe_android_demo/MainActivity;)
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41581c50)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.sh1r0.caffe_android_demo, PID: 6843
                  java.lang.UnsatisfiedLinkError: dlopen failed: 
                      at java.lang.Runtime.loadLibrary(Runtime.java:364)
                      at java.lang.System.loadLibrary(System.java:555)
                      at com.sh1r0.caffe_android_demo.MainActivity.<clinit>(MainActivity.java:57)
                      at java.lang.Class.newInstanceImpl(Native Method)
                      at java.lang.Class.newInstance(Class.java:1208)
                      at android.app.Instrumentation.newActivity(Instrumentation.java:1064)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:143)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5398)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by sh1r0** [comment]
Please refer to https://github.com/sh1r0/caffe-android-demo/issues/40#issuecomment-256854306, thanks.
